services:
  # Main RAG application
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    volumes:
      # Mount docs directory for PDF processing
      - ./docs:/app/docs:ro
      # Mount logs directory
      - ./logs:/app/logs
      # Mount cache directory for Hugging Face models
      - ./hf_cache:/app/.cache/huggingface
    depends_on:
      chromadb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rag-network

  # ChromaDB vector database
  chromadb:
    image: chromadb/chroma:0.6.3
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ANONYMIZED_TELEMETRY=false
    volumes:
      - ./chromadb_data:/chroma/chroma
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8000/api/v1/heartbeat || exit 1"]
      interval: 10s
      retries: 2
      start_period: 5s
      timeout: 10s
    networks:
      - rag-network


volumes:
  chromadb_data:
    driver: local
  hf_cache:
    driver: local

networks:
  rag-network:
    driver: bridge
